/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marcus_cmakedemo_JniNative */

#ifndef _Included_com_marcus_cmakedemo_JniNative
#define _Included_com_marcus_cmakedemo_JniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marcus_cmakedemo_JniNative
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_marcus_cmakedemo_JniNative_getStringFromJni
  (JNIEnv *, jobject);

/*
 * Class:     com_marcus_cmakedemo_JniNative
 * Method:    jniArrayAdd
 * Signature: ([II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_marcus_cmakedemo_JniNative_jniArrayAdd
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_marcus_cmakedemo_JniNative
 * Method:    dataTypeMapping
 * Signature: (BSCIFDJZ[ILjava/lang/String;Lcom/marcus/cmakedemo/ObjectClass;)V
 */
JNIEXPORT void JNICALL Java_com_marcus_cmakedemo_JniNative_dataTypeMapping
  (JNIEnv *, jobject, jbyte, jshort, jchar, jint, jfloat, jdouble, jlong, jboolean, jintArray, jstring, jobject);

/*
 * Class:     com_marcus_cmakedemo_JniNative
 * Method:    getStringCritical
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_marcus_cmakedemo_JniNative_getStringCritical
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_marcus_cmakedemo_JniNative
 * Method:    getStringUTFRegion
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_marcus_cmakedemo_JniNative_getStringUTFRegion
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_marcus_cmakedemo_JniNative
 * Method:    sumIntArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_marcus_cmakedemo_JniNative_sumIntArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_marcus_cmakedemo_JniNative
 * Method:    intToInt2DArray
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[[[F
 */
JNIEXPORT jobjectArray JNICALL Java_com_marcus_cmakedemo_JniNative_intToInt2DArray
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
